# Generated by Django 2.2.3 on 2019-07-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='hasAttachment',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='attachment',
            field=models.TextField(blank=True, default=None, max_length=8000),
        ),
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.TextField(blank=True, default=None, max_length=8000),
        ),
    ]
