# Generated by Django 2.2.3 on 2019-07-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20190709_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(default=models.EmailField(max_length=254), max_length=30),
        ),
    ]
